// <auto-generated />
using System;
using FieldServiceCRM.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FieldServiceCRM.Migrations
{
    [DbContext(typeof(CrmDbContext))]
    [Migration("20260208203859_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("FieldServiceCRM.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactPerson")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "123 Main St, City, ST 12345",
                            ContactPerson = "John Smith",
                            CreatedDate = new DateTime(2026, 2, 8, 20, 38, 57, 524, DateTimeKind.Utc).AddTicks(7799),
                            Email = "john@acme.com",
                            IsActive = true,
                            Name = "Acme Corp",
                            Phone = "(555) 123-4567"
                        },
                        new
                        {
                            Id = 2,
                            Address = "456 Oak Ave, Town, ST 23456",
                            ContactPerson = "Sarah Johnson",
                            CreatedDate = new DateTime(2026, 2, 8, 20, 38, 57, 524, DateTimeKind.Utc).AddTicks(7805),
                            Email = "sarah@techsol.com",
                            IsActive = true,
                            Name = "Tech Solutions Inc",
                            Phone = "(555) 234-5678"
                        },
                        new
                        {
                            Id = 3,
                            Address = "789 Pine Rd, Village, ST 34567",
                            ContactPerson = "Mike Chen",
                            CreatedDate = new DateTime(2026, 2, 8, 20, 38, 57, 524, DateTimeKind.Utc).AddTicks(7808),
                            Email = "mike@greenvalley.com",
                            IsActive = true,
                            Name = "Green Valley Restaurant",
                            Phone = "(555) 345-6789"
                        });
                });

            modelBuilder.Entity("FieldServiceCRM.Models.Invoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("InvoiceDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PaidDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TaxAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("InvoiceNumber")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("FieldServiceCRM.Models.InvoiceItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("InvoiceId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId");

                    b.ToTable("InvoiceItems");
                });

            modelBuilder.Entity("FieldServiceCRM.Models.Job", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ActualHours")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int?>("AssignedTechnicianId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("EstimatedHours")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int?>("InvoiceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ScheduledDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AssignedTechnicianId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("InvoiceId");

                    b.HasIndex("ScheduledDate");

                    b.HasIndex("Status");

                    b.ToTable("Jobs");
                });

            modelBuilder.Entity("FieldServiceCRM.Models.Technician", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("HourlyRate")
                        .HasColumnType("decimal(10,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Technicians");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "tom@fieldservice.com",
                            HireDate = new DateTime(2020, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HourlyRate = 75m,
                            IsActive = true,
                            Name = "Tom Martinez",
                            Phone = "(555) 111-2222",
                            Specialization = "HVAC"
                        },
                        new
                        {
                            Id = 2,
                            Email = "lisa@fieldservice.com",
                            HireDate = new DateTime(2019, 7, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HourlyRate = 80m,
                            IsActive = true,
                            Name = "Lisa Park",
                            Phone = "(555) 222-3333",
                            Specialization = "Electrical"
                        },
                        new
                        {
                            Id = 3,
                            Email = "james@fieldservice.com",
                            HireDate = new DateTime(2021, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HourlyRate = 70m,
                            IsActive = true,
                            Name = "James Wilson",
                            Phone = "(555) 333-4444",
                            Specialization = "Plumbing"
                        },
                        new
                        {
                            Id = 4,
                            Email = "maria@fieldservice.com",
                            HireDate = new DateTime(2022, 5, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HourlyRate = 65m,
                            IsActive = true,
                            Name = "Maria Garcia",
                            Phone = "(555) 444-5555",
                            Specialization = "General Maintenance"
                        });
                });

            modelBuilder.Entity("FieldServiceCRM.Models.Invoice", b =>
                {
                    b.HasOne("FieldServiceCRM.Models.Customer", "Customer")
                        .WithMany("Invoices")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("FieldServiceCRM.Models.InvoiceItem", b =>
                {
                    b.HasOne("FieldServiceCRM.Models.Invoice", "Invoice")
                        .WithMany("Items")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("FieldServiceCRM.Models.Job", b =>
                {
                    b.HasOne("FieldServiceCRM.Models.Technician", "AssignedTechnician")
                        .WithMany("AssignedJobs")
                        .HasForeignKey("AssignedTechnicianId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FieldServiceCRM.Models.Customer", "Customer")
                        .WithMany("Jobs")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FieldServiceCRM.Models.Invoice", "Invoice")
                        .WithMany("Jobs")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AssignedTechnician");

                    b.Navigation("Customer");

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("FieldServiceCRM.Models.Customer", b =>
                {
                    b.Navigation("Invoices");

                    b.Navigation("Jobs");
                });

            modelBuilder.Entity("FieldServiceCRM.Models.Invoice", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("Jobs");
                });

            modelBuilder.Entity("FieldServiceCRM.Models.Technician", b =>
                {
                    b.Navigation("AssignedJobs");
                });
#pragma warning restore 612, 618
        }
    }
}
